version: '3.4'
services:
  db:
    image: postgres:15.1
    container_name: postgres-15
    restart: always
    environment:
      POSTGRES_USER: luciano
      POSTGRES_PASSWORD: 789789
      POSTGRES_DB:
    ports:
      - "5432:5432"